### PR TITLE
Switching all docker tags to latest

### PR DESCRIPTION
**Pull request by pivotal-jamie-klassen**
https://github.com/pivotal-cf/pfs-ci/issues/10

### CODE REVIEW

**Comment by trisberg** [comment]
Using `latest` is a pain when developing with minikube since k8s can't dor the `ifNotPresent` check and ends up always downloading the latest from DocherHub. What is the actual issue we are solving here?

**Comment by markfisher** [comment]
we're using `0.0.1-SNAPSHOT` now in all the docker build configs (in the POMs), and the local dev experience is better with a version other than "latest" because you can replace locally without always pulling

**Comment by freynca** [comment]
@trisberg We're not particular about `latest` vs anything else. However, CI needs to tag these images, and there is no semver-based `sk8s` release process at this moment. Can use a hardcoded `0.0.1-SNAPSHOT` for now.

**Comment by trisberg** [comment]
Is this for the sk8s artifacts or for the samples? Seems to be a mix in the PR.

**Pull request closed without merging**
