### PR TITLE
Change delete command to delete function and jobs (for now) resources

### PR DESCRIPTION
**Pull request by trisberg**
- jobs should probably be removed by controller at some point

- adding delete instructions to READMEs

- changing README links to be relative (helps when viewing locally)

### CODE REVIEW

**Comment by markfisher** [comment]
merged with amended comment (for 50 char limit) as https://github.com/markfisher/sk8s/commit/6d5636f230e7365d8451d8645c665c472a0543ea

**Comment by markfisher** [comment]
apparently setting the owner reference on the Job resource (referencing the Function resource) is not sufficient for cascading garbage collection. I added that here (but it doesn't work): https://github.com/markfisher/sk8s/commit/35338b1ba0e7a3e5b9f4e151186bf1c0a0cb97a9

so, I assume we need to set the `deleteOptions.propagationPolicy` on the owning resource (Function in our case) as described here: https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/

many resources (such as `Deployment` resources) have that set by default

cc @ericbottard

**Comment by markfisher** [comment]
I realized the owner reference should be in the Job metadata (rather than its Pod template), so I changed that here (but it still doesn't cascade by default): https://github.com/markfisher/sk8s/commit/bab3da03123e252f2077c171282bee0c1363c293

**Comment by trisberg** [comment]
Are you on k8s v1.8? I think it's a new feature. My minikube is v1.7.5.

**Comment by markfisher** [comment]
I went ahead and pushed this for now (the controller deletes the jobs based on the function label), and the owner-reference is being set on the Job metadata... so maybe be that will provide an option for cascading deletes at some point: https://github.com/markfisher/sk8s/commit/703ff6832513e30b50ec87054e89a1291b7a1d54

**Comment by ericbottard** [comment]
Yes we need 1.8+ for this to happen magically (haven't managed to run a 1.8+ minikube yet, hitting RBAC issues). Still doesn't hurt and serves "documentation" purposes nevertheless.

**Pull request closed without merging**
